version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Clearing old dependencies..."
      - rm -rf node_modules package-lock.json
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo "Running React build..."
      - npm run build || true   # don’t stop immediately
      - echo "=== Build Logs (if failed) ==="
      - cat /codebuild/output/**/npm-cache/_logs/*.log || true
artifacts:
  files:
    - '**/*'
  base-directory: build
